name: Build Packages

on:
  workflow_call:
  workflow_dispatch:

jobs:
  build:
    name: Build Packages
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4.1.1


    - name: Build package
      shell: bash
      run: |
        ./build-all.sh
      working-directory: ${{ github.workspace }}

    - name: Upload package
      uses: actions/upload-artifact@v4.3.1
      with:
        if-no-files-found: error
        name: build
        path: |
          build/*
